### ISSUE TITLE
Profile: Connect Bots with Github, Gitlab, Gitbucket

### ISSUE THREAD

**Issue by EgoriusRus** [anthive/website#123]

**Comment by kezlya** [comment]
## Step 1
![Screen Shot 2020-06-24 at 2 05 16 PM](https://user-images.githubusercontent.com/2000153/85544673-e6c4f700-b623-11ea-909a-1d998d838597.png)

```
Create a new site
From zero to hero, three easy steps to get your site on AntHive.

Connect to Git provider
Pick a repository
Build options, and deploy!
Continuous Deployment
Choose the Git provider where your site’s source code is hosted. When you push to Git, we run your build tool of choice on our servers and deploy the result.

GitHub
GitLab
Bitbucket
```

**Comment by kezlya** [comment]
## Step 2
![Screen Shot 2020-06-24 at 2 09 59 PM](https://user-images.githubusercontent.com/2000153/85545232-6eab0100-b624-11ea-83a5-33aabe5a3a9d.png)

**Comment by kezlya** [comment]
Moved to profile project
