### ISSUE TITLE
Metatags: Add Title for each Page

### ISSUE THREAD

**Issue by EgoriusRus** [anthive/website#174]
# Set og: tags and double check using this tool 
https://socialsharepreview.com/?url=https://anthive.io

## Home page
TITLE:   **AntHive.IO**
DESCRIPTION: **Is a platform to learn and practice programming skills in a fun way. Code your strategy in Python, JS, PHP. Golang, C# or C++  Compete in tournaments.**
Image: 
![AntHive IO](https://user-images.githubusercontent.com/2000153/89730118-9aebd700-da44-11ea-9b37-846e83376abb.jpg)
 
## Games page
TITLE:   **AntHive.IO - Recent games**
DESCRIPTION: **Is a platform to learn and practice programming skills in a fun way. Code your strategy in Python, JS, PHP. Golang, C# or C++  Compete in tournaments.**

## Rules

**Comment by kezlya** [comment]
https://totheweb.com/learning_center/tools-search-engine-simulator/

**Comment by kezlya** [comment]
done in PR #211
