### ISSUE TITLE
Fix Vue component and base file names

### ISSUE THREAD

**Issue by dlutton** [anthive/website#177]
Per the Vue style guide: 
Base filenames: https://vuejs.org/v2/style-guide/#Base-component-names-strongly-recommended
Component filenames: https://vuejs.org/v2/style-guide/#Single-file-component-filename-casing-strongly-recommended

**Comment by kezlya** [comment]
Good point @dlutton we will address this in Sprint 10

**Comment by kezlya** [comment]
Possible module to use with regex for filenames that vue recommends https://www.npmjs.com/package/eslint-plugin-filenames
