### ISSUE TITLE
Ошибки при подключении репозитория к учетной записи

### ISSUE THREAD

**Issue by Cuba-Taba** [anthive/website#197]
В Anthive создал учетку с именем Сергей Пелюшенко (почта cubataba2007@gmail.com).
В GitHub создал пустой репозиторий с названием AntHiveBot
В Anthive не смог его подключить, так как структура репозитория была не верной.
Затем узнал, что нужно было делать импорт шаблонного репозитория.
Удалил свой репозиторий.
Сделал импорт шаблоннного репозитория на языке python. Имя репозитория выбрал как и у старого AntHiveBot.
В соответствующем файле указал имя Cuba. Но так как имя не соответствовало имени в аккаунте репозиторий снова не прошел верификацию.
Сменил имя на "Сергей Пелюшенко". Ошибка имени пропала. Но при подгрузке коммитов каждый коммит показывал какую-то ошибку.
Подумал, что имя на кириллице не проходит. Но сменить имя в настройках аккаунта нельзя.

Решил завести новую учетку и новый репозиторий.
Завел новую учетку на почту serp2007@yandex.ru с именем Cuba.
Старый репозиторий удалил и завел новый (сделав импорт), но с тем же названием AntHiveBot.
Сделал один коммит с изменением имени в файле на Cuba.

Попытался подключить репозиторий к учетке, но при загрузке коммитов опять увидел ошибки.

Error: exit status 1
Logs: unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/kezlya/go/src/anthive-runner/docker/python3: no such file or directory

Причем самое интересное, что я увидел как грузятся коммиты с предыдущего репозитория который был удален. И один новый коммит.

Может это из-за того, что имя репозитория я оставлял прежнее?

**Comment by Cuba-Taba** [comment]
Текущий репозиторий подключаемого бота "https://github.com/Cuba-Taba/AntHiveBot"

**Comment by kezlya** [comment]
Thank you for report.
This issue has been fixed. The problem was in incorrect lang name in ANTHIVE file. It should say just **`python`**
