### ISSUE TITLE
Логотип “ANTHIVE” (Header), при разрешении экрана от 1200х800 смещается вправо

### ISSUE THREAD

**Issue by IrinaPodolyak** [anthive/website#249]
Шаги воспроизведения:
Открыть ссылку: https://anthive.netlify.app/

ФР: Логотип “ANTHIVE” смещается вправо 
ОР: Логотип “ANTHIVE” на одном уровне с левой частью контента

Окружение: Google Chrome Версия 86.0.4240.198,  разрешение экрана 1200х800

<img width="1232" alt="Снимок экрана 2020-11-22 в 20 03 18" src="https://user-images.githubusercontent.com/74865312/99910357-8f27d600-2cfe-11eb-8978-c6895c3d4439.png">

**Comment by Klimonov** [comment]
Move to separate project
