### ISSUE TITLE
Request rematch

### ISSUE THREAD

**Issue by kezlya** [anthive/website#295]
### PR https://github.com/kezlya/anthive-profile/pull/166

Urls with parameter `rematch`  new-game/?rematch=7tRf6kT8exBSs0
Should configure settings of the game to match requested rematch
![Screen Shot 2020-11-25 at 11 32 58 AM](https://user-images.githubusercontent.com/2000153/100202151-fc5f8500-2f11-11eb-8f6b-9e753b04de0e.png)

**Comment by Klimonov** [comment]
PR https://github.com/kezlya/anthive-profile/pull/165

**Comment by Klimonov** [comment]
Done https://github.com/kezlya/anthive-profile/pull/165

**Comment by kezlya** [comment]
Map settings work but players not selected.
