### ISSUE TITLE
Remove "Forgot Password?" for Create account step

### ISSUE THREAD

**Issue by Klimonov** [anthive/website#300]
![Screenshot 2020-11-25 at 14 42 55](https://user-images.githubusercontent.com/28136131/100226281-90404980-2f30-11eb-9cdf-071e784e1c4f.png)

**Comment by IrinaPodolyak** [comment]
QA Passed
https://anthive-development.web.app/signin
<img width="541" alt="Снимок экрана 2020-12-01 в 13 18 16" src="https://user-images.githubusercontent.com/74865312/100727838-d0dc0f00-33d7-11eb-9b28-0a0a10194ec3.png">
Google Chrome Версия 87.0.4280.67 1200х800
