### ISSUE TITLE
Add space between button and text

### ISSUE THREAD

**Issue by Klimonov** [anthive/website#301]
![Screenshot 2020-11-25 at 14 42 37](https://user-images.githubusercontent.com/28136131/100226383-b8c84380-2f30-11eb-8782-312dd45e2572.png)

**Comment by IrinaPodolyak** [comment]
QA Passed
https://anthive-development.web.app/signin 
<img width="543" alt="Снимок экрана 2020-12-01 в 13 14 13" src="https://user-images.githubusercontent.com/74865312/100727370-2cf26380-33d7-11eb-9cad-c0bca7c010eb.png">
Google Chrome Версия 87.0.4280.67 1200х800
