### ISSUE TITLE
Centered and add space between for social buttons

### ISSUE THREAD

**Issue by Klimonov** [anthive/website#302]
![Screenshot 2020-11-25 at 15 01 49](https://user-images.githubusercontent.com/28136131/100226505-e7461e80-2f30-11eb-83d1-3e4e8fa47d20.png)

**Comment by IrinaPodolyak** [comment]
QA Passed 
https://anthive-development.web.app/signin
![IMG_4528](https://user-images.githubusercontent.com/74865312/100773887-83c95e80-3412-11eb-952d-786b80ae8cd0.jpg)

iPhone 8 Plus, Safari
