### ISSUE TITLE
Add style for active language button (Create profile, Settings)

### ISSUE THREAD

**Issue by Klimonov** [anthive/website#303]
![Screenshot 2020-11-25 at 15 31 04](https://user-images.githubusercontent.com/28136131/100228363-9c79d600-2f33-11eb-9c7c-227c58492c55.png)
![Screenshot 2020-11-25 at 15 31 20](https://user-images.githubusercontent.com/28136131/100228379-a4397a80-2f33-11eb-8794-5793cd0c8b65.png)

**Comment by IrinaPodolyak** [comment]
QA Passed
https://anthive-development.web.app/signin
<img width="546" alt="Снимок экрана 2020-12-01 в 12 56 32" src="https://user-images.githubusercontent.com/74865312/100726529-1b5c8c00-33d6-11eb-872f-c94befbc910c.png">

https://anthive-development.web.app/settings
<img width="1160" alt="Снимок экрана 2020-12-01 в 20 01 02" src="https://user-images.githubusercontent.com/74865312/100771870-f8e76480-340f-11eb-8241-28d24c59e7cc.png">

Google Chrome Версия 87.0.4280.67, 1200х800
