### ISSUE TITLE
Improve Game component UX/UI

### ISSUE THREAD

**Issue by kezlya** [anthive/website#306]
![Screen Shot 2020-11-30 at 9 10 45 AM](https://user-images.githubusercontent.com/2000153/100575404-0eb03900-32ed-11eb-85a0-d4ae24b1909a.png)

### Game must show:
- Bots from 1 - 7
- Age
- Time ago
- View replay
------ optional------
background

### Each Bot must have:
- Avatar
- Username
- Version
- Lang
- Rank
------- optional -----
- Skin
- ART
- Errors

**Comment by kezlya** [comment]
Maybe represent games as tiles not rows:
![Screen Shot 2020-11-30 at 10 35 30 AM](https://user-images.githubusercontent.com/2000153/100580962-eda11580-32f7-11eb-81b8-96d672b6776a.png)

**Comment by Klimonov** [comment]
Move to separate project
