### ISSUE TITLE
Change fav icon on profile

### ISSUE THREAD

**Issue by kezlya** [anthive/website#307]

**Comment by IrinaPodolyak** [comment]
QA Passed
https://anthive-development.web.app/dashboard
<img width="325" alt="Снимок экрана 2020-12-01 в 20 09 05" src="https://user-images.githubusercontent.com/74865312/100772972-57611280-3411-11eb-935b-f77483765b17.png">

Google Chrome Версия 87.0.4280.67 1200х800
