### ISSUE TITLE
When select repository check for Anthive file.

### ISSUE THREAD

**Issue by kezlya** [anthive/website#309]
On the screen with list of repositories.

When repository selected call API to create bot. If API return error show it
Looks like this repository not an Anthive bot. You need to have ANTHIVE file in the root of your repository.

![Screen Shot 2020-11-30 at 10 52 04 AM](https://user-images.githubusercontent.com/2000153/100582618-92bced80-32fa-11eb-8c15-e7b8d92fb39a.png)

**Comment by Klimonov** [comment]
Obsolete
