### ISSUE TITLE
open avatar-template.png: no such file or directory

### ISSUE THREAD

**Issue by ArcticSpaceFox** [anthive/website#361]
Date: 12-12-2020
Platform: Win64
URL: https://profile.anthive.io/signin
Browser: Mozilla/5.0 (Windows NT 10.0

**Comment by kezlya** [comment]
Thank you for report @Sm03leBr00t 
Adding screenshot
![Screen Shot 2020-12-12 at 5 47 16 PM](https://user-images.githubusercontent.com/2000153/101986939-26e76700-3ca2-11eb-9dd9-6ea3f6e8f68a.png)

**Comment by ArcticSpaceFox** [comment]
No problem 😅👌 really your site did everything automatically
