### ISSUE TITLE
Fix language slider on CodeEditor

### ISSUE THREAD

**Issue by EgoriusRus** [anthive/website#378]
![image](https://user-images.githubusercontent.com/54712243/102462043-5b6c7180-405a-11eb-87fa-3d75064ccd97.png)
Need to add arrows for scroll lang list, now arrows is invisible

**Comment by kezlya** [comment]
@EgoriusRus this related to https://github.com/anthive/website/issues/348

Let's wait for design for it @Viktoria1358

**Comment by Klimonov** [comment]
Move to separate project
