### ISSUE TITLE
Friday code review feedback

### ISSUE THREAD

**Issue by kezlya** [anthive/website#382]
- [ ] Refactor GetImage method. Should we use Mixin? or something else?

### Bots.vue 

- [ ] Remove BEM line 5
- [ ] Remove Store Layer from all API example linen 43 and line 49
- [ ] Remove Create bot method from line 50 just do redirect to separate page
- [ ] Import animation in global css
- [ ] Line 67 and 70 Remove overwrite break points. Use grid.
- [ ] Line 80 remove border radius
- [ ] Line 81-82 use grid
- [ ] Use global color
- [ ] Height should not change if something does not fit we should use ... 
- [ ] https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/
- [ ] text overflow

### CreatBot

- [ ] Load editor only on Bot create page
- [ ] Line 72 Remove commented out code
- [ ] vueX remove
- [ ] Split Sandbox component and Repository components
- [ ] Create common folder and have Constants.js Import it
- [ ] Functions Names should be Verbs
- [ ] Line 203 InitEditors get rid of promises
- [ ] CreateSandbox bot remove promises
- [ ] Line 321 CreateGitHub bot Depricated remove
- [ ] Sort css properties Lint or Prettifier
- [ ] Refactor Target page component so we don't have to use 100% height in each component
- [ ] All fonts should be global and use font family
- [ ] Declare upto 8 options of font style use vars: weight-size-color.  https://guides.kontur.ru/
- [ ] Remove custom scrollbar

**Comment by Klimonov** [comment]
Obsolete. We no longer have these components
