### ISSUE TITLE
Create Game does not work when trying to link to Github

### ISSUE THREAD

**Issue by thisIsTheWei** [anthive/website#425]
I logged in with my Google account to the site and want to create a new game. When clicking the Github button in **Continuous Integration**, it initiate the process but the github request is throwing 404 error and failed creating new game.
Extra note, I can't login using Github account because I think the email is associating with my Google account.

**Comment by kezlya** [comment]
Thank you for reporting this @darthkimo We identified the issue. Will ping you when it's fixed!

**Comment by kezlya** [comment]
Hi @darthkimo when you have some downtime could you please try it agian on staging https://anthive.netlify.app/ ?
I think the issue has been fixed.

**Comment by thisIsTheWei** [comment]
Yes, it is working now. Thanks!

**Comment by Klimonov** [comment]
Fixed
