### ISSUE TITLE
Visual bug on vertical bot chip

### ISSUE THREAD

**Issue by Klimonov** [anthive/website#509]
<img width="655" alt="Screenshot 2021-02-24 at 09 32 36" src="https://user-images.githubusercontent.com/28136131/108960240-a4f2c180-7686-11eb-87a3-3005c9ee5a7f.png">

**Comment by kezlya** [comment]
Also add skin to the top left corner.

**Comment by Klimonov** [comment]
@EgoriusRus 
![Screenshot 2021-02-26 at 09 20 30](https://user-images.githubusercontent.com/28136131/109263345-2592f880-7814-11eb-921b-321c9302b2a0.png)
