### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by Klimonov** [anthive/website#543]
<img width="743" alt="Screenshot 2021-03-17 at 14 44 08" src="https://user-images.githubusercontent.com/28136131/111462238-3f4aa000-872f-11eb-9495-8b7c38f2f4dc.png">

<img width="736" alt="Screenshot 2021-03-17 at 14 43 30" src="https://user-images.githubusercontent.com/28136131/111462188-2e9a2a00-872f-11eb-826b-23abd1605d55.png">

**Comment by kezlya** [comment]
Let's do search on FE for now
