### ISSUE TITLE
word breaks in header on profile page

### ISSUE THREAD

**Issue by sadiolem** [anthive/website#573]
<img width="757" alt="Capture d’écran 2021-10-06 à 16 44 59" src="https://user-images.githubusercontent.com/43725229/136214854-35fb0b3e-e98f-40f0-b836-bf4cbc1c7fa7.png">

**Comment by kezlya** [comment]
@Mad-Moks please retest and close this one.

**Comment by Mad-Moks** [comment]
![Снимок экрана 2021-10-25 в 14 59 14](https://user-images.githubusercontent.com/83368881/138691322-fa51b2d7-2a5e-4c96-afce-cb91235dfb43.png)
![Снимок экрана 2021-10-25 в 14 59 28](https://user-images.githubusercontent.com/83368881/138691332-06901989-1172-45f4-94f1-acbed44bf356.png)

**Comment by Mad-Moks** [comment]
but i caught a pixel and the left menu is not working correctly
![Снимок экрана 2021-10-25 в 15 00 17](https://user-images.githubusercontent.com/83368881/138691567-3b343600-0db4-409a-bcbd-ddfffca9c527.png)
@sadiolem @kezlya
